version: "3"
services:
  tcs:
    image: jetbrains/teamcity-server:latest
    deploy:
        resources:
            limits:
                memory: 2G
    ports:
      - "80:8111"
  tca:
    image: android_tc_agent_image:latest
    deploy:
        resources:
            limits:
                memory: 6G
    environment:
      - SERVER_URL=tca:8111
