version: "3"
services:
  tc_server:
    image: jetbrains/teamcity-server:latest
    volumes:
      - "/home/phate/docker/android_ci/volumes_testing/teamcity/data:/data/teamcity_server/datadir"
    deploy:
        resources:
            limits:
                memory: 2G
    ports:
      - "8080:8111"
  tc_agent:
    image: android_tc_agent_image:latest
    deploy:
        resources:
            limits:
                memory: 6G
    environment:
      - SERVER_URL=tc_server:8111
