version: "3"
services:
  tcs:
    image: jetbrains/teamcity-server:latest
    deploy:
        resources:
            limits:
                memory: 2G
    ports:
      - "8080:8111"
  tca:
    image: nowy_android_sdk_container:latest    
    deploy:
        resources:
            limits:
                memory: 6G
    environment:
      - SERVER_URL=tcs:8111
